### ISSUE TITLE
Deprecation warning about `set-output`

### ISSUE THREAD

**Issue by fatbasstard** [terraform-linters/tflint-load-config-action#126]
HI, getting a deprecation warning when using this:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by bendrucker** [comment]
Version? This should have been fixed by #66.

**Comment by fatbasstard** [comment]
Implemented it using the sample from the readme:

```yaml
      - uses: terraform-linters/tflint-load-config-action@v0
        with:
          source-repo: me/tflint-config
```

Assuming this is the "latest"?
