### ISSUE TITLE
Random intermittent Http Error

### ISSUE THREAD

**Issue by dreinhardt-terminus** [terraform-linters/tflint-load-config-action#154]
I keep getting the below error at random times intermittently. The workflow will run fine for awhile then it will randomly start breaking. Any idea what the cause is? Probably going to have to get rid of tflint if this keeps happening.

![image](https://github.com/terraform-linters/tflint-load-config-action/assets/85892019/54e44859-7b2e-499e-adf7-e4d50c5832eb)

I use the action within a composite action like below:

```yaml
  steps:
    - name: TFLint - Load Shared Config
      uses: terraform-linters/tflint-load-config-action@v1
      with:
        source-repo: GetTerminus/terminus-github-actions
        source-path: shared-files/.tflint.hcl
        source-ref: ${{ inputs.tflint_config_branch }}
        destination-path: ./.tflint.hcl
        token: ${{ env.GITHUB_TOKEN }}
```
